version: '3.8'

services:
  service-one:
    build: ./go-service/.
    ports:
      - 8080:8080
    environment:
      - COLLECTOR_ADDR=otel-collector:55680
      - SERVICE_NAME=service_one
      - CALL_SERVICE_ADDR=http://service-two:8080

  service-two:
    build: ./go-service/.
    depends_on:
      - otel-collector
    ports:
      - 8081:8080
    environment:
      - COLLECTOR_ADDR=otel-collector:55680
      - SERVICE_NAME=service_two
      - CALL_SERVICE_ADDR=http://ot-sample-app:4567/outgoing-http-call

  service-three:
    image: java-otel
    depends_on:
      - otel-collector
    ports:
      - 8082:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:55680
      - OTEL_EXPORTER_OTLP_INSECURE=true

  # Otel Collector
  otel-collector:
#    image: otel/opentelemetry-collector-dev:latest
    build: ./collector/.
    command: ["--config=/etc/otel-collector-config.yaml", "--log-level=DEBUG"]

    volumes:
      - ./collector/config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ~/.aws:/root/.aws

    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_REGION=eu-west-1
      - AWS_PROFILE=sandbox-accounts-platform-services-PowerUser

    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55678"       # OpenCensus receiver
      - "55670:55679" # zpages extension
      - "9464:9464"   # zipkin
      - "55680:55680" # zipkin
      - "55681:55681" # zipkin

    depends_on:
      - zipkin-all-in-one
      - jaeger

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest

    volumes:
      - ./collector/config/prometheus.yaml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"

  # Sample web application which will generate Metrics and Traces data if the enable API is called
  # src - https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/sample-apps/spark
  ot-sample-app:
    image: aottestbed/aws-otel-collector-java-sample-app:0.6.0
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:55680
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=AOCDockerDemo,service.name=AOCDockerDemoService
      - AWS_REGION=eu-west-1
      - AWS_PROFILE=sandbox-accounts-platform-services-PowerUser
      - LISTEN_ADDRESS=0.0.0.0:4567 # web server endpoint
    volumes:
      - ~/.aws:/root/.aws # test auto generated trace on S3 access
    ports:
      - "4567:4567"   # http sample requests
    depends_on:
      - otel-collector
