version: '3.8'

services:
  service-one:
    build: ./go-service/.
    ports:
      - 8080:8080
    environment:
      - COLLECTOR_ADDR=otel-collector:55680
      - SERVICE_NAME=service_one
      - CALL_SERVICE_ADDR=http://service-two:8080

  service-two:
    build: ./go-service/.
    depends_on:
      - otel-collector
    ports:
      - 8081:8080
    environment:
      - COLLECTOR_ADDR=otel-collector:55680
      - SERVICE_NAME=service_two
      - CALL_SERVICE_ADDR=http://service-three:8080

  service-three:
    build: ./jre-service/.
    depends_on:
      - otel-collector
    ports:
      - 8082:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:55680
      - OTEL_EXPORTER_OTLP_METRIC_ENDPOINT=http://otel-collector:55680
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=service.name=service_three

  # Otel Collector
  otel-collector:
#    image: otel/opentelemetry-collector-dev:latest
    build: ./collector/.
    command: ["--config=/etc/otel-collector-config.yaml", "--log-level=DEBUG"]

    volumes:
      - ./collector/config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ~/.aws:/root/.aws

    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_REGION=eu-west-1
      - AWS_PROFILE=sandbox-accounts-platform-services-PowerUser

    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55678"       # OpenCensus receiver
      - "55670:55679" # zpages extension
      - "9464:9464"   # zipkin
      - "55680:55680" # zipkin
      - "55681:55681" # zipkin

    depends_on:
      - zipkin-all-in-one
      - jaeger

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest

    volumes:
      - ./collector/config/prometheus.yaml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"
